# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the vesc_comp branch
  push:
    branches: [ vesc_comp ]
  pull_request:
    branches: [ vesc_comp ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      # ruleid: allowed-unsecure-commands
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v2
    - name: log untrusted output
      run: |

        # disable command workflow processing
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

        # log untrusted output
        echo "untrusted output"

        # enable workflow command processing
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: '9-2020-q2'
    - name: make
      run: make
      
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: python tools/xiaotea/Scripts/prepareZip_online.py      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/tools/zip_output
        name: ${{ github.run_number }}
        retention-days: 5
