# This is a basic workflow to help you get started with Actions

name: Release on tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the vesc_comp branch
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # ruleid: allowed-unsecure-commands
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v2
    
    - name: log untrusted output
      run: |
        # disable command workflow processing
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
        # log untrusted output
        echo "untrusted output"
        # enable workflow command processing
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
        
    - name: 'Build M365'
      uses: docker://wsbu/stm32cubeide:latest
      with:
        entrypoint: /opt/stm32cubeide/stm32cubeide
        args: --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -build m365/Debug -importAll /github/workspace/
            
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ github.workspace }}/m365/STM32CubeIDE/Debug/m365.bin
        asset_name: m365.bin
        asset_content_type: application/octet-stream

    - name: Send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: '${{ secrets.TELEGRAM_TO }}'
        token: '${{ secrets.TELEGRAM_TOKEN }}'
        message: |
          New release available : ${{ github.ref }}
          Commit message: ${{ github.event.commits[0].message }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
